# Global Setting for the Database
# PageSize, StartRID, etc..
PAGESIZE = 512
POOLSIZE = 32
INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
MERGENUMBER = 128
MERGETIME = 1
BUFFERLOCK = 0